"""One-pager HTML renderer — generates client-ready summary from ReviewResult."""

from __future__ import annotations

import html
import logging
from datetime import date
from typing import Optional

from ...schemas.review_result import ReviewResult

logger = logging.getLogger("market-lens")

_TEMPLATE = """\
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: 'Hiragino Sans', 'Segoe UI', 'Noto Sans JP', sans-serif;
    color: #1a1e2e; background: #fff; line-height: 1.7; padding: 40px 48px;
    max-width: 800px; margin: 0 auto;
  }}
  .header {{ border-bottom: 3px solid #6c63ff; padding-bottom: 16px; margin-bottom: 28px; }}
  .header h1 {{ font-size: 1.4rem; font-weight: 700; color: #6c63ff; }}
  .header .subtitle {{ font-size: .9rem; color: #4a5068; margin-top: 4px; }}
  .header .date {{ font-size: .8rem; color: #6e7590; margin-top: 2px; }}
  .summary {{ background: #f5f7fa; border-left: 4px solid #6c63ff; padding: 16px 20px; margin-bottom: 28px; border-radius: 0 8px 8px 0; font-size: .92rem; }}
  section {{ margin-bottom: 24px; }}
  section h2 {{ font-size: 1.05rem; font-weight: 700; margin-bottom: 12px; padding-bottom: 6px; border-bottom: 1px solid #d0d5e0; }}
  .good h2 {{ color: #059669; }}
  .keep h2 {{ color: #0891b2; }}
  .improve h2 {{ color: #d97706; }}
  .test h2 {{ color: #6c63ff; }}
  .evidence h2 {{ color: #6e7590; }}
  .positioning h2 {{ color: #7c3aed; }}
  .positioning table {{ border: 1px solid #d0d5e0; }}
  .positioning th, .positioning td {{ border: 1px solid #d0d5e0; padding: 6px 10px; text-align: left; }}
  .positioning th {{ background: #f5f7fa; font-size: .8rem; font-weight: 600; }}
  ul {{ padding-left: 1.4em; }}
  li {{ margin-bottom: 6px; font-size: .9rem; }}
  li strong {{ font-weight: 600; }}
  .action {{ color: #4a5068; font-size: .85rem; }}
  .footer {{ margin-top: 32px; padding-top: 12px; border-top: 1px solid #d0d5e0; font-size: .75rem; color: #6e7590; text-align: center; }}
  @media print {{
    body {{ padding: 20px; }}
    .footer {{ position: fixed; bottom: 10px; left: 0; right: 0; }}
  }}
</style>
</head>
<body>
<div class="header">
  <h1>{title}</h1>
  <div class="subtitle">{subtitle}</div>
  <div class="date">{review_date}</div>
</div>
<div class="summary">{summary}</div>
{sections}
<div class="footer">Generated by Market Lens AI &mdash; Creative Review</div>
</body>
</html>"""


def _esc(text: str) -> str:
    return html.escape(text, quote=True)


def _render_good_points(result: ReviewResult) -> str:
    items = "\n".join(
        f"  <li><strong>{_esc(p.point)}</strong> &mdash; {_esc(p.reason)}</li>"
        for p in result.good_points
    )
    return f'<section class="good"><h2>良い点</h2>\n<ul>\n{items}\n</ul></section>'


def _render_keep_as_is(result: ReviewResult) -> str:
    items = "\n".join(
        f"  <li><strong>{_esc(p.point)}</strong> &mdash; {_esc(p.reason)}</li>"
        for p in result.keep_as_is
    )
    return f'<section class="keep"><h2>守るべき点</h2>\n<ul>\n{items}\n</ul></section>'


def _render_improvements(result: ReviewResult) -> str:
    items = "\n".join(
        f'  <li><strong>{_esc(p.point)}</strong> &mdash; {_esc(p.reason)}'
        f'<br><span class="action">Action: {_esc(p.action)}</span></li>'
        for p in result.improvements
    )
    return f'<section class="improve"><h2>改善提案</h2>\n<ul>\n{items}\n</ul></section>'


def _render_test_ideas(result: ReviewResult) -> str:
    items = "\n".join(
        f"  <li><strong>{_esc(t.hypothesis)}</strong>"
        f" (変数: {_esc(t.variable)}, 期待効果: {_esc(t.expected_impact)})</li>"
        for t in result.test_ideas
    )
    return f'<section class="test"><h2>次に試すテスト案</h2>\n<ul>\n{items}\n</ul></section>'


def _render_evidence(result: ReviewResult) -> str:
    items = "\n".join(
        f"  <li>[{_esc(e.evidence_type.value)}] {_esc(e.evidence_source)} &mdash; {_esc(e.evidence_text)}</li>"
        for e in result.evidence
    )
    return f'<section class="evidence"><h2>根拠・出典</h2>\n<ul>\n{items}\n</ul></section>'


def _render_positioning_insights(result: ReviewResult) -> str:
    """Render positioning insights section for competitor compare reviews."""
    if not result.positioning_insights:
        return ""
    rows = []
    for ins in result.positioning_insights:
        rows.append(
            f"  <tr>"
            f"<td>{_esc(ins.dimension)}</td>"
            f"<td>{_esc(ins.our_position)}</td>"
            f"<td>{_esc(ins.competitor_position)}</td>"
            f"<td>{_esc(ins.gap_analysis)}</td>"
            f"<td>{_esc(ins.recommendation)}</td>"
            f"</tr>"
        )
    table_rows = "\n".join(rows)
    return (
        '<section class="positioning"><h2>ポジショニング分析</h2>\n'
        '<table style="width:100%;border-collapse:collapse;font-size:.85rem;">\n'
        "  <tr><th>比較軸</th><th>自社</th><th>競合</th><th>ギャップ</th><th>推奨</th></tr>\n"
        f"{table_rows}\n"
        "</table></section>"
    )


def render_onepager_html(
    result: ReviewResult,
    *,
    title: str = "クリエイティブレビュー サマリー",
    subtitle: str = "",
    review_date: Optional[str] = None,
) -> str:
    """Render a client-ready one-pager HTML from ReviewResult.

    Returns the complete HTML string.
    """
    if review_date is None:
        review_date = date.today().isoformat()

    section_parts = [
        _render_good_points(result),
        _render_keep_as_is(result),
        _render_improvements(result),
        _render_test_ideas(result),
        _render_evidence(result),
        _render_positioning_insights(result),
    ]
    sections = "\n".join(s for s in section_parts if s)

    return _TEMPLATE.format(
        title=_esc(title),
        subtitle=_esc(subtitle),
        review_date=_esc(review_date),
        summary=_esc(result.summary),
        sections=sections,
    )
