// Deliberately small customer-facing subset. Importing Clerk's complete
// localization catalog adds every billing/admin string to the customer bundle.
export const clerkJaLocalization = {
  locale: 'ja-JP',
  backButton: '戻る',
  dividerText: 'または',
  formButtonPrimary: '続ける',
  formButtonPrimary__verify: '確認する',
  formFieldAction__forgotPassword: 'パスワードをお忘れですか？',
  formFieldInputPlaceholder__emailAddress: 'メールアドレスを入力',
  formFieldInputPlaceholder__emailAddress_username: 'メールアドレスまたはユーザー名',
  formFieldInputPlaceholder__password: 'パスワードを入力',
  formFieldInputPlaceholder__phoneNumber: '電話番号を入力',
  formFieldLabel__emailAddress: 'メールアドレス',
  formFieldLabel__emailAddress_username: 'メールアドレスまたはユーザー名',
  formFieldLabel__password: 'パスワード',
  formFieldLabel__phoneNumber: '電話番号',
  signIn: {
    start: {
      title: '{{applicationName}} にログイン',
      titleCombined: '{{applicationName}} へ進む',
      subtitle: '招待されたメールアドレスで本人確認してください',
      subtitleCombined: '招待されたメールアドレスで本人確認してください',
      actionText: 'アカウントをお持ちでないですか？',
      actionLink: 'アカウントを作成',
      actionLink__use_email: 'メールアドレスを使用',
      actionLink__use_phone: '電話番号を使用',
    },
    password: {
      title: 'パスワードを入力',
      subtitle: 'このアカウントのパスワードを入力してください',
      actionLink: '別の方法を使用',
    },
    emailCode: {
      title: 'メールを確認',
      subtitle: '{{applicationName}} へ進む',
      formTitle: '確認コード',
      resendButton: 'コードを再送信',
    },
    totpMfa: {
      title: '二段階認証',
      subtitle: '認証アプリに表示された確認コードを入力してください',
      formTitle: '確認コード',
    },
    noAvailableMethods: {
      title: 'ログインできません',
      subtitle: '利用できる本人確認方法がありません',
      message: '管理者へお問い合わせください。',
    },
  },
  signUp: {
    start: {
      title: 'アカウントを作成',
      titleCombined: 'アカウントを作成',
      subtitle: 'メールアドレスの確認から始めます',
      subtitleCombined: 'メールアドレスの確認から始めます',
      actionText: 'すでにアカウントをお持ちですか？',
      actionLink: 'ログイン',
      actionLink__use_email: 'メールアドレスを使用',
      actionLink__use_phone: '電話番号を使用',
    },
    emailCode: {
      title: 'メールアドレスを確認',
      subtitle: 'メールに届いた確認コードを入力してください',
      formTitle: '確認コード',
      formSubtitle: 'メールアドレスに送信したコードを入力してください',
      resendButton: 'コードを再送信',
    },
  },
  organizationSwitcher: {
    action__closeOrganizationSwitcher: '企業選択を閉じる',
    action__createOrganization: '企業を作成',
    action__invitationAccept: '参加する',
    action__manageOrganization: '企業を管理',
    action__openOrganizationSwitcher: '契約企業を選ぶ',
    notSelected: '契約企業が選択されていません',
    personalWorkspace: '個人用',
  },
  unstable__errors: {
    form_code_incorrect: '確認コードが正しくありません。',
    form_identifier_not_found: '一致するアカウントが見つかりませんでした。',
    form_param_format_invalid__email_address: 'メールアドレスの形式を確認してください。',
    form_password_incorrect: 'パスワードが正しくありません。',
    form_password_or_identifier_incorrect: 'メールアドレスまたはパスワードを確認してください。',
    organization_not_found_or_unauthorized: 'この企業へ参加していません。別の企業を選んでください。',
  },
}
